steps:
  - name: gcr.io/cloud-builders/gcloud
    args:
      - kms
      - decrypt
      - --ciphertext-file=keys/buildkite-packer.enc
      - --plaintext-file=keys/buildkite-packer
      - --location=global
      - --keyring=packer
      - --key=buildkite
  - id: packer
    name: hashicorp/packer:1.4.1
    entrypoint: 'sh'
    args: [
      '-c',
      'packer build -var project_id=$PROJECT_ID -var buildkite_token=$$BUILDKITE_KEY -var version=$TAG_NAME template-builder-ubuntu-18.04.json'
    ]
    secretEnv: ['BUILDKITE_KEY']
secrets:
  - kmsKeyName: projects/shinncloud/locations/global/keyRings/packer/cryptoKeys/buildkite
    secretEnv:
      BUILDKITE_KEY: CiQAb9WAmHrjGlqFQvDLPpAxuA6QxDw6DfJzYy5DVKtzXlm5QFESWwAEUrqlDtdU+e63FUZEqxZorrHlbM7rBGMfoy1hx6VZSRE792DLKIu3KRbXBEqhLshw6kcE/Y3yKmJFtXQ0hib0IWEYwHSVN7zYmnIPbo8oPNmkFqaeZUXHrgo=
