steps:
  - id: packer
    name: hashicorp/packer:1.4.1
    entrypoint: 'sh'
    args: [
      '-c',
      'packer build -var project_id=$PROJECT_ID -var buildkite_token=$$BUILDKITE_KEY -var version=$TAG_NAME template-builder-ubuntu-18.04.json'
    ]
    secretEnv: ['BUILDKITE_KEY']
  - id: template
    name: gcr.io/cloud-builders/gcloud
    args: [
      'compute',
      '--project=shinncloud',
      'instance-templates',
      'create',
      '$TAG_NAME',
      '--scopes=https://www.googleapis.com/auth/devstorage.read_only,https://www.googleapis.com/auth/logging.write,https://www.googleapis.com/auth/monitoring.write,https://www.googleapis.com/auth/servicecontrol,https://www.googleapis.com/auth/service.management.readonly,https://www.googleapis.com/auth/trace.append',
      '--image=$TAG_NAME',
      '--image-project=shinncloud',
      '--boot-disk-size=50GB'
    ]
  - id: rolling-update
    name: gcr.io/cloud-builders/gcloud
    args: [
      'beta',
      'compute',
      'instance-groups',
      'managed',
      'rolling-action',
      'start-update',
      'builders',
      '--region=$_REGION',
      '--version=template=$TAG_NAME'
    ]
substitutions:
  _REGION: us-east1
secrets:
  - kmsKeyName: projects/shinncloud/locations/global/keyRings/packer/cryptoKeys/buildkite
    secretEnv:
      BUILDKITE_KEY: CiQAb9WAmBb+7LrPfmU6O72dFf2Kx24c5Iv8z7AP4E5hVF83PBoSWwAEUrql0FaSZMvdagwXFnKDDq72kUQoMoBusy/zZPNS3Rf5EfhJdopmY6EXc2+h7hni4J4eTVw+1YrJ+zNtOAX9Ffo206GDORUevRfnh4wLUaRRd7Jq5BN7hXY=
