steps:
  - name: 'gcr.io/$PROJECT_ID/packer'
    args:
      - build
      - -var
      - project_id=$PROJECT_ID
      - -var
      - buildkite_token=$BUILDKITE_KEY
      - template-builder-ubuuntu-18.04.json
    secretEnv: ['BUILDKITE_KEY']
secrets:
  - kmsKeyName: projects/shinncloud/locations/global/keyRings/packer/cryptoKeys/buildkite
    secretEnv:
      PASSWORD: CiQAb9WAmBb+7LrPfmU6O72dFf2Kx24c5Iv8z7AP4E5hVF83PBoSWwAEUrql0FaSZMvdagwXFnKDDq72kUQoMoBusy/zZPNS3Rf5EfhJdopmY6EXc2+h7hni4J4eTVw+1YrJ+zNtOAX9Ffo206GDORUevRfnh4wLUaRRd7Jq5BN7hXY=
