steps:
  - label: ':packer: Packer Validate'
    plugins:
      - docker#v3.3.0:
          image: hashicorp/packer:1.4.1
          command:
            - validate
            - template-builder-ubuntu-18.04.json
  - wait
  - label: ":packer: Packer Build"
    plugins:
      - docker#v3.3.0:
          image: hashicorp/packer:1.4.1
          environment: ["BUILDKITE_KEY", "BUILDKITE_TAG"]
          entrypoint: ""
          command:
            - bin/packer_build
